### ISSUE TITLE
pizza-logger Unnecessary dependency

### ISSUE THREAD

**Issue by frozenfrank** [devops329/devops#104]
Why does the pizza-logger package have a dependency on [mysql2](https://www.npmjs.com/package/pizza-logger?activeTab=dependencies), when the code itself doesn't actually require it?

This pizza-logger package itself is totally self-sufficient and could actually be used with any DB system. That should be reflected in the required dependencies.

**Comment by leesjensen** [comment]
Good question. @isawamoose - Any reason you can't remove mysql2 from the package dependency?

**Comment by leesjensen** [comment]
Unfortunately it is actually necessary. Those sneaky hackers have evil plans in store.
