### ISSUE TITLE
Deliverable 10 — Load Tests file breaks CI Pipeline

### ISSUE THREAD

**Issue by frozenfrank** [devops329/devops#107]
## Overview

When following the directions to submit the `loadTests/loginAndOrder.js` file are followed, the linter breaks. **This also breaks the CI deployment pipeline.**

## Screenshots

Local environment:

<img width="752" alt="image" src="https://github.com/user-attachments/assets/d8d928a6-988e-4b15-b1e7-bfc678cacd6a">

GitHub Actions CI Pipeline:

<img width="960" alt="image" src="https://github.com/user-attachments/assets/385b56d2-75ea-4f7f-a31b-8b269e3e14a4">

## Discussion

At a high level, there are two ways to fix this issue:
1. Exclude the `loadTests/` folder from linting
    * Pro: **It's easy to implement** (see https://github.com/frozenfrank/jwt-pizza-service/commit/ff080e63f6592a4803c8bb76c2a4a6711ca1bb7e and the [corresponding CI run](https://github.com/frozenfrank/jwt-pizza-service/actions/runs/12092084287))
    * Con: None of the load tests will be linted at all, which means they could diverge from project standards
3. Somehow figure out how to ignore that rule
    * Pro: The majority of the file would be linted according to project standards
    * Con: I don't know how the parse error would be avoided

## Recommendation
I would recommend that some comment be added to the [Deliverable 10 Assignment](https://github.com/devops329/devops/blob/main/instruction/deliverable10LoadTesting/deliverable10LoadTesting.md#-assignment) section to discuss this issue.

**Comment by leesjensen** [comment]
I believe the [instruction](https://github.com/devops329/devops/blob/main/instruction/deliverable11ChaosTesting/deliverable11ChaosTesting.md#-assignment) states to store your load test script to JWT Pizza, not JWT Pizza Service.

If you do that you won't have a problem with the linter.

**Comment by frozenfrank** [comment]
I definitely missed that detail 🤦‍♂️

**Comment by frozenfrank** [comment]
Is that the main reason you have us store files in the `jwt-pizza` repo as opposed to the `jwt-pizza-service` repo? As far as the responsibilities are related, it actually seems like the load tests and chaos reports are more related to the service than to the front end.

**Comment by leesjensen** [comment]
It wasn't a conscious decision other than I recorded the use of the
frontend to drive the load testing and so it felt like a frontend test, but
in reality I think you are right. Not breaking the linter is just a lucky
side effect.
