### ISSUE TITLE
Is Chaos Testing still an assignment?

### ISSUE THREAD

**Issue by frozenfrank** [devops329/devops#110]
The [reading page](https://github.com/devops329/devops/blob/main/instruction/chaosTesting/chaosTesting.md#-assignment) and [modules page](https://github.com/devops329/devops/blob/main/instruction/modules.md#failure-management) say so, but there is no Canvas assignment to turn in.

I enjoyed the process of completing it though! (Screenshot of my dashboard showing the triggering and resolution of an issue.)
<img width="542" alt="image" src="https://github.com/user-attachments/assets/84eee625-e84b-4e7a-a80b-b60afddc6135">

**Comment by leesjensen** [comment]
That is awesome! I actually think that is one of the more enjoyable assignments. Nothing like making your code crash!

I think it just got lost in Canvas, but I have completely removed it as an assignment now.
