### ISSUE TITLE
Confusion About JWT Pizza GitHub URL Submission Location

### ISSUE THREAD

**Issue by frozenfrank** [devops329/devops#59]
## Overview
In the reading, it made it sound like the AutoGrader would automatically find my repo based on the magic `jwt-pizza` repo name and the GitHub username provided on [My Profile](https://cs329.cs.byu.edu/profile) page. However, then I was asked at the end to submit the direct URL to Canvas.

I had expected to provide GitHub related information to the AutoGrader. Some clarification about how this is supposed to be would be appreciated.

## Sources
Here are the conflicting sources of information:
[Forking the Repository:](https://github.com/devops329/devops/blob/main/instruction/jwtPizzaClient/jwtPizzaClient.md#forking-the-application-teams-repository)
> Create the fork by pressing the Create fork button. For the AutoGrader to find your repo, leave the name of the repository jwt-pizza.

[Assignment:](https://github.com/devops329/devops/blob/main/instruction/jwtPizzaClient/jwtPizzaClient.md#-assignment)
> Once you are done, go over to Canvas and submit the URL of your forked repository.

**Comment by leesjensen** [comment]
The canvas submission is not used by the autograder. It is only meant as an aid to the learner to remind them to complete the work.

The autograder asks for the GitHub url for the learner and assumes both the path for pizza and pizza-service as indicated in the instruction while passing off the future deliverables.

I suppose we could remove the need to submit the canvas assignment, but it does seem to provide some value to the learner.
